const CustomImage = {
  back: require('../assets/back.png'),
  call: require('../assets/call.png'),
  location: require('../assets/location.png'),
  search: require('../assets/search.png'),
  delete: require('../assets/delete.png'),
  back: require('../assets/back.png'),
  call: require('../assets/call.png'),
  location: require('../assets/location.png'),
  logo: require('../assets/logo.png'),
  vip: require('../assets/vip.png'),
  edit: require('../assets/edit.png'),
  message: require('../assets/message.png'),
  demo: require('../assets/demo.png'),
  codedemo: require('../assets/codedemo.png'),
  user: require('../assets/user.png'),
  previewImage: require('../assets/previewImage.png'),
  request: require('../assets/request.png'),
  requestride: require('../assets/requestride.png'),
  requestrideactive: require('../assets/requestrideactive.png'),

  unitedkingdom: require('../assets/unitedkingdom.png'),
  germany: require('../assets/germany.png'),
  china: require('../assets/china.png'),
  japan: require('../assets/japan.png'),
  france: require('../assets/france.png'),
  india: require('../assets/india.png'),
  save: require('../assets/save.png'),
  profile: require('../assets/profile.png'),
  camera: require('../assets/camera.png'),
  plus: require('../assets/plus.png'),
  minus: require('../assets/minus.png'),
  home: require('../assets/home.png'),
  chaticon: require('../assets/chaticon.png'),
  auto: require('../assets/auto.jpg'),

  rightSwipe: require('../assets/swipeRight.png'),
  leftSwipe: require('../assets/swipeLeft.png'),
};
export default CustomImage;
