const CustomImage = {
  back: require('../assets/back.png'),
  call: require('../assets/call.png'),
  location: require('../assets/location.png'),
  search: require('../assets/search.png'),
  delete: require('../assets/delete.png'),
  back: require('../assets/back.png'),
  call: require('../assets/call.png'),
  location: require('../assets/location.png'),
  logo: require('../assets/logo.png'),
  message: require('../assets/message.png'),
  demo: require('../assets/demo.png'),
  codedemo: require('../assets/codedemo.png'),
  user: require('../assets/user.png'),

  unitedkingdom: require('../assets/unitedkingdom.png'),
  germany: require('../assets/germany.png'),
  china: require('../assets/china.png'),
  japan: require('../assets/japan.png'),
  france: require('../assets/france.png'),
  india: require('../assets/india.png'),
  save: require('../assets/save.png'),
  profile: require('../assets/profile.png'),
  camera: require('../assets/camera.png'),
  plus: require('../assets/plus.png'),
  minus: require('../assets/minus.png'),
  home: require('../assets/home.png'),
};
export default CustomImage;
