import {StyleSheet, Dimensions} from 'react-native';
import {Colors} from './Colors';
import fontSize from './Fonts';
import {horizScale, vertScale} from './Layout';
const styles = StyleSheet.create({
  backText: {
    color: Colors.white,
    marginHorizontal: horizScale(5),
    fontSize: fontSize.input,
    fontWeight: '700',
  },
  smallCircle: {
    borderRadius: horizScale(7),
    borderWidth: horizScale(0.5),
    // marginHorizontal: horizScale(8),
    paddingHorizontal: horizScale(3),
    marginVertical: horizScale(7),
  },
  smallIconVehical: {
    height: horizScale(50),
    width: horizScale(55),
    resizeMode: 'center',
  },
  tabbarIconActive: {
    borderRadius: horizScale(20),
    backgroundColor: Colors.white,
    padding: horizScale(4.4),
  },
  imageBig: {
    width: 300,
    height: 400,
    resizeMode: 'contain',
    borderRadius: horizScale(12),
    borderWidth: horizScale(1),
    borderColor: Colors.mainColor,
    backgroundColor: Colors.mainColorDim,
  },
  homeIcon: {
    height: horizScale(30),
    width: horizScale(30),
    resizeMode: 'contain',
    marginHorizontal: horizScale(20),
  },
  normalText: {
    color: Colors.black,
    fontSize: fontSize.medium,
  },
  finger: {
    height: horizScale(50),
    width: horizScale(50),
    borderRadius: horizScale(25),
    backgroundColor: Colors.transparent,
    backfaceVisibility: 'visible',
    borderWidth: horizScale(2),
    borderColor: Colors.black,
    position: 'absolute',
  },
  smallText: {
    color: Colors.darkgrey,
    fontSize: fontSize.small,
    fontWeight: '400',
    paddingHorizontal: horizScale(20),
    textAlign: 'left',
  },
  modalBox: {
    backgroundColor: Colors.white,
    width: horizScale(300),
    borderRadius: horizScale(15),
    alignSelf: 'center',
  },
  modalBox1: {
    backgroundColor: Colors.white,
    width: '90%',
    borderRadius: horizScale(15),
    alignSelf: 'center',
    flex: 0.85,
    overflow: 'hidden',
  },
  selected: {
    backgroundColor: Colors.mainColor,
    borderRadius: horizScale(30),
    elevation: 3,
    padding: horizScale(8),
    width: '37%',
    // width: horizScale(120),
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    paddingVertical: horizScale(16),
  },
  unSelected: {
    borderWidth: horizScale(1),
    borderColor: Colors.mainColor,
    borderRadius: horizScale(30),
    padding: horizScale(8),
    // width: horizScale(120),
    width: '37%',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    paddingVertical: horizScale(16),
  },
  selectedText: {
    color: Colors.white,
    fontSize: fontSize.small,
    fontWeight: '600',
    paddingHorizontal: horizScale(10),
    textAlign: 'center',
  },
  unSelectedText: {
    fontSize: fontSize.small,
    fontWeight: '600',
    color: Colors.mainColor,
    paddingHorizontal: horizScale(10),
    textAlign: 'center',
  },
  TextH3: {
    color: Colors.mainColor,
    textAlignVertical: 'center',
    paddingLeft: horizScale(20),
    fontSize: fontSize.h3,
    fontWeight: 'bold',
  },
  TextH5: {
    color: Colors.mainColor,
    textAlignVertical: 'center',
    paddingLeft: horizScale(20),
    fontSize: fontSize.h5,
    fontWeight: '600',
  },
  TextMedium: {
    color: Colors.black,
    textAlignVertical: 'center',
    fontSize: fontSize.medium,
    fontWeight: '400',
  },
  headerView: {
    marginHorizontal: horizScale(10),
    marginVertical: horizScale(15),
  },
  button: {
    paddingVertical: vertScale(15),
    width: '80%',
    backgroundColor: Colors.mainColor,
    borderRadius: horizScale(40),
    alignSelf: 'center',
    justifyContent: 'center',
  },
  homeBtn: {
    paddingVertical: vertScale(15),
    width: '45%',
    borderColor: Colors.mainColor,
    borderRadius: horizScale(40),
    alignSelf: 'center',
    justifyContent: 'center',
  },
  smallbutton: {
    paddingVertical: vertScale(5),
    width: '40%',
    backgroundColor: Colors.mainColor,
    borderRadius: horizScale(40),
    alignSelf: 'center',
    justifyContent: 'center',
  },
  buttonText: {
    textAlign: 'center',
    color: Colors.white,
    fontSize: fontSize.regular,
    fontWeight: '700',
  },
  floatingcontainerstyle: {
    marginTop: vertScale(15),
    marginHorizontal: horizScale(20),
    borderBottomWidth: vertScale(2),
  },
  floatinginputstyle: {
    color: Colors.black,
    fontSize: fontSize.medium,
    marginTop: horizScale(5),
    fontWeight: '700',
  },
  labelstyle: {
    paddingVertical: horizScale(5),
    color: Colors.black,
  },
  floatinglabelstyle: {
    fontSizeFocused: fontSize.small,
    fontSizeBlurred: fontSize.medium,
    colorBlurred: Colors.black,
    colorFocused: Colors.black,
    fontWeight: 'bold',
  },
  floatingContainer: {
    height: horizScale(60),
    borderWidth: horizScale(1),
    marginHorizontal: horizScale(40),
    borderRadius: horizScale(10),
  },
  logoImage: {
    marginVertical: horizScale(30),
    height: horizScale(80),
    width: horizScale(260),
    alignSelf: 'center',
    resizeMode: 'contain',
  },
  bigImage: {
    marginVertical: horizScale(30),
    height: horizScale(210),
    width: horizScale(260),
    alignSelf: 'center',
    resizeMode: 'cover',
  },
  codeGeneretorImage: {
    height: horizScale(280),
    width: horizScale(280),
    alignSelf: 'center',
    resizeMode: 'contain',
    backgroundColor: 'black',
  },
  codeGeneretorContainer: {
    height: horizScale(380),
    width: horizScale(380),
    borderWidth: horizScale(4),
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  codeGeneretorText: {
    letterSpacing: horizScale(5),
    fontSize: fontSize.medium,
    fontWeight: '700',
    color: Colors.mainColor,
  },
  homeAppName: {
    textAlign: 'center',
    fontSize: fontSize.h4,
    fontWeight: '700',
    color: Colors.mainColor,
    textShadowColor: Colors.darkgrey,
    textShadowRadius: 1,
  },
  titleText: {
    fontFamily: 'americankestral1_2',
    textAlign: 'center',
    fontSize: fontSize.h2,
    color: Colors.black,
  },
  rowCenter: {
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    top: horizScale(10),
  },
  rowSpaceEvenly: {
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginHorizontal: horizScale(10),
    // backgroundColor: 'red',
  },
  rowCenterItem: {
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  addressHeading: {
    marginHorizontal: horizScale(20),
    backgroundColor: Colors.grey,
    padding: horizScale(15),
    borderRadius: horizScale(10),
  },
  container: {
    flex: 1,
    backgroundColor: Colors.white,
    width: Dimensions.get('window').width,
  },
  containerLinearGradient: {
    flex: 1,
    height: Dimensions.get('window').height,
    width: Dimensions.get('window').width,
  },
  containerLinearGradientModal: {
    flex: 1,
    height: '100%',
  },
  smallLinearGradient: {
    height: horizScale(100),
    width: Dimensions.get('window').width,
    backfaceVisibility: 'visible',
    backgroundColor: 'rgba(52,52,52,0.1)',
    position: 'absolute',
    bottom: 0,
  },
  homeHeading: {
    color: Colors.mainColor,
    textAlignVertical: 'center',
    paddingLeft: horizScale(20),
    fontSize: fontSize.h4,
    fontWeight: 'bold',
  },
  homeBtnView: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  homeDec: {
    color: Colors.mainColor,
    textAlignVertical: 'center',
    paddingHorizontal: horizScale(20),
    lineHeight: vertScale(30),
    fontSize: fontSize.h5,
    fontWeight: '600',
  },
  chooseText: {
    color: Colors.mainColor,
    textAlignVertical: 'center',
    paddingLeft: horizScale(20),
    fontSize: fontSize.h5,
    fontWeight: 'bold',
  },
  headingText: {
    color: Colors.mainColor,
    textAlignVertical: 'center',
    paddingLeft: horizScale(20),
    fontSize: fontSize.input,
    fontWeight: 'bold',
  },
  forgetPassword: {
    color: Colors.mainColor,
    textAlignVertical: 'center',
    paddingRight: horizScale(20),
    fontSize: fontSize.medium,
    fontWeight: '700',
    textDecorationLine: 'underline',
  },
  listContainer: {
    marginHorizontal: horizScale(2),
    marginVertical: horizScale(10),
    backgroundColor: Colors.white,
    elevation: 3,
    borderRadius: horizScale(15),
    padding: horizScale(20),
  },
  list2ColumContainer: {
    marginHorizontal: horizScale(2),
    marginVertical: horizScale(15),
    backgroundColor: Colors.white,
    elevation: 3,
    borderRadius: horizScale(15),
    padding: horizScale(20),
    marginHorizontal: horizScale(30),
  },
  name: {
    color: Colors.blue,
    fontSize: fontSize.regular,
    fontWeight: '600',
  },
  username: {
    color: Colors.blue,
    fontSize: fontSize.h5,
    fontWeight: 'bold',
  },
  email: {
    color: Colors.black,
    fontSize: fontSize.small,
    fontWeight: '500',
  },
  smallIcon: {
    height: horizScale(20),
    width: horizScale(20),
    resizeMode: 'contain',
  },

  smallCircleImage: {
    height: horizScale(80),
    width: horizScale(80),
    borderRadius: horizScale(40),
    resizeMode: 'contain',
  },
  backView: {
    flexDirection: 'row',
    marginLeft: horizScale(20),
    marginTop: horizScale(10),
    alignItems: 'center',
  },
  backText: {
    color: Colors.darkgrey,
    marginLeft: horizScale(10),
    fontSize: fontSize.medium,
  },
  infoView: {
    margin: horizScale(20),
    padding: horizScale(30),
    backgroundColor: Colors.blueLight,
    borderRadius: horizScale(15),
  },
  testUnderline: {
    marginHorizontal: horizScale(20),
    height: horizScale(45),
    borderBottomWidth: horizScale(0.8),
    borderColor: Colors.grey,
    textAlignVertical: 'bottom',
    color: Colors.black,
    fontWeight: '600',
    fontSize: fontSize.regular,
  },
});
export default styles;
